spring:
  datasource:
    url: jdbc:mysql://sud-mysql:3306/book?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: sudarshan123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    locations:
      - classpath:scripts/book
      - classpath:scripts/data